=== maxmelnyk/task14_JSON/JSON/src/main/resources/json/gemSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "gems",
  "$comment": "Array of gems",
  "type": "array",
  "items": {
    "$comment": "Gem describe",
    "type": "object",
    "properties": {
      "number": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "preciousness": {
        "type": "string"
      },
      "origin": {
        "type": "string"
      },
      "visualParameters": {
        "$comment": "parameters of this gem",
        "type": "object",
        "properties": {
          "color": {
            "type": "string"
          },
          "transparency": {
            "type": "number",
            "minimum": 1.0,
            "maximum": 100.0
          },
          "wayOfCutting": {
            "type": "integer",
            "minimum": 4,
            "maximum": 15
          }
        }
      },
      "value": {
        "type": "integer"
      }
    }
  }
}

=== maxmelnyk/task14_JSON/JSON/src/main/resources/json/gem.json
[
  {
    "number": 1,
    "name": "Ruby",
    "preciousness": "precious",
    "origin": "Asia",
    "visualParameters": {
      "color": "red",
      "transparency": 80,
      "wayOfCutting": 9
    },
    "value": 1
  },
  {
    "number": 2,
    "name": "Diamond",
    "preciousness": "precious",
    "origin": "Africa",
    "visualParameters": {
      "color": "white",
      "transparency": 100,
      "wayOfCutting": 15
    },
    "value": 5
  },
  {
    "number": 3,
    "name": "Diamond",
    "preciousness": "precious",
    "origin": "Africa",
    "visualParameters": {
      "color": "yellow",
      "transparency": 85,
      "wayOfCutting": 8
    },
    "value": 3
  },
  {
    "number": 4,
    "name": "Zirconium",
    "preciousness": "semi precious",
    "origin": "India",
    "visualParameters": {
      "color": "white",
      "transparency": 90,
      "wayOfCutting": 9
    },
    "value": 1
  }
]
